.\" 
.TH "r2test" "8" "1.0.0" "Moises Silva" "Administration"
.SH "NAME"
r2test \- MFC/R2 call setup test program
.SH "SYNOPSIS"
.PP 
\fBr2test\fR <config file>
.SH "DESCRIPTION"
.PP 
This tool can be used to test the OpenR2 library with MFC/R2 lines

.SH "SEE ALSO"
.PP 
r2test.conf(5)
.SH "AUTHOR"
.PP 
This manual page was written by Alexandre Cavalcante Alencar
<alexandre.alencar@gmail.com>
.PP 
Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 3 any later version
published by the Free Software Foundation.
